Health-check tuning: adjust check interval.

diff --git a/scripts/pynoser_cron_health b/scripts/pynoser_cron_health
--- a/scripts/pynoser_cron_health
+++ b/scripts/pynoser_cron_health
@@ -1,7 +1,7 @@
 #!/bin/bash
 ERR_LEVEL=3
-ERR_INTVL="2 hours"
-ERR_THRESH_PER_INTVL=20
+ERR_INTVL="1 hours"
+ERR_THRESH_PER_INTVL=10
 
 errors=$(
 python2 -u /opt/pynoser/pynoser/manage.py dbshell <<EOF
@@ -9,12 +9,13 @@ select count(*) from djutil_errorlog
 where log_level>=${ERR_LEVEL}
   and time_stamp > datetime('now', '-${ERR_INTVL}')
 EOF
-)
+) 2>&1 || exit 42
+
+echo -n "${errors} errors  in the last ${ERR_INTVL}."
 
 if [[ $errors -ge $ERR_THRESH_PER_INTVL ]]; then
-    echo "${errors} errors  in the last ${ERR_INTVL}!"
+    echo " Failed!"
     exit 1
 fi
 
 exit 0
-
